### PR TITLE
Fix JSON property index.

### LINKED ISSUE #661: Better error message when "prop_name" is not specified for a JSON column
```python
from gino.dialects.asyncpg import JSONB
from myproject.main import db

class MyModel(db.Model):
    __tablename__ = "models"

    id = db.Column(db.BigInteger(), primary_key=True)
    profile_json = db.Column(JSONB(), nullable=False, server_default="{}")

    profile = db.JSONProperty()
```

This causes the error:

```
...
    exp = self.make_expression(getattr(owner, self.prop_name)[self.name])
  [Previous line repeated 312 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

The fix is to add `prop_name='profile_json'` to the `JSONProperty()` declaration, but without docs and an error message, it is hard to know that.

### PR DESCRIPTION
**Pull request by fantix**
* also support JSON property on non-crud base
* add docs for JSON property
* fixes #661

### CODE REVIEW

**Comment by fantix** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/gino/declarative.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/python-gino/gino/pullRequest?prid=5460597&bid=17896683)

**Comment by wwwjfy** [comment]
The rest of changes are fine, but it doesn't fix #661 where the default JSON column name `profile` is used as a JSONProperty.

**Comment by fantix** [comment]
Oh right! CRF added, thanks!

**Comment by fantix** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/gino/declarative.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/python-gino/gino/pullRequest?prid=5460597&bid=17896683)

**Comment by fantix** [comment]
Thanks! Error message updated to be more clear.

**Comment by fantix** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/gino/declarative.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/python-gino/gino/pullRequest?prid=5460597&bid=17896683)

**Pull request merged**
