### PR TITLE
Answering "How to do bulk insert / update?"

### PR DESCRIPTION
**Pull request by austincollinpena**
I came across [this conversation](https://github.com/python-gino/gino/issues/314) talking about bulk insertion. I found the FAQ to have a question corresponding to the discussion with no answer.

I took [wwwjfy's comment](https://github.com/python-gino/gino/issues/314#issuecomment-415979324), gave it some context, and added it to the FAQ.

Before considering this pull request, perhaps it would be wiser to examine [this implementation](https://github.com/python-gino/gino/issues/314l) by Arthur264 as another example:

```
await insert(model.__table__).values(items).on_conflict_do_nothing().gino.scalar()
```

### CODE REVIEW

**Comment by fantix** [comment]
Thank you so much for this PR! I'm reviewing a bit later this weekend.

**Comment by austincollinpena** [comment]
Happy to help! I love the library and I hope to make as many small contributions as I can. If you have feedback for me it's always appreciated.

**Comment by fantix** [comment]
I'm glad to hear that. Yes, an example of bulk update would be great - bulk upsert is another bonus.

**Comment by roycefanproxy** [comment]
Hi,
does this method returns all the inserted data?

**Pull request merged**
