### PR TITLE
added content into alembic.rst

### PR DESCRIPTION
**Pull request by xnuinside**
@fantix, hi! 

I want to add content to page with `Use Alembic` in Docs. I checked .rst syntax in IDE, but I got several issues in Sphinx not relative to this page - I will attach screen with issues in comment. So I did not build docs. 

Please review, any fixes are welcome!

### CODE REVIEW

**Comment by xnuinside** [comment]
issues with docs build 
Screen Shot 2020-05-16 at 6 27 55 PM

**Comment by fantix** [comment]
Much thanks! Please use `make serve` in `docs` dir, I put the required envvars in the `Makefile`. Will add instructions into docs too.

**Comment by xnuinside** [comment]
@fantix, yes this works, thanks! docs was builded, no errors, from visual side oks, but maybe need fix some texts. Will wait for review from you :)

**Comment by xnuinside** [comment]
@fantix, fixes merged

**Comment by fantix** [comment]
Thanks!

**Pull request merged**
